# AI 프로그래밍 과제 2

In [34]:
import numpy as np
import time

# 문제 1 (4 points)

In [35]:
array_a = np.arange(0,100)
print(array_a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


NumPy의 np.sum()함수를 이용하여 배열안에 모든 원소들의 합을 구함.

In [36]:
start_array1 = time.time()
sum_array = np.sum(array_a)
print("Sum of all elements in array_a: ", sum_array)
end_array1 = time.time()
result_array1 = end_array1 - start_array1

Sum of all elements in array_a:  4950


NumPy의 array_a 배열을 Python의 기본 list_a 리스트로 변환

In [37]:
list_a = array_a.tolist()
print(list_a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


## 프로그래밍 문제 1-1: Python의 리스트 list_a 를 이용하여 np.sum(array_a)과 같은 계산을 수행하는 total_sum() 함수를 작성하시오.

In [38]:
start_list1 = time.time()
def total_sum(a):
    elements = 0
    for i in a:
        elements += i
    return elements

위에 구현한 total_sum() 함수를 호출하여 반환된 결과값(sum_list)을 출력함.

In [39]:
# 함수 호출
sum_list = total_sum(list_a)
# 결과 출력
print("Sum of all elements in list_a: ", sum_list)
end_list1 = time.time()
result_list1 = end_list1 - start_list1

Sum of all elements in list_a:  4950



NumPy 배열 array_a의 형태를 reshape()를 이용하여 변환하고 array_b에 할당함.

In [40]:
array_b = array_a.reshape(5,20)
print(array_b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


NumPy의 np.sum()함수를 이용하여 각각의 열 별로 합을 구함.

In [41]:
start_array2 = time.time()
column_sum_array = np.sum(array_b, axis=0)
print("Column sum of array_b: ", column_sum_array)
end_array2 = time.time()
result_array2 = end_array2 - start_array2

Column sum of array_b:  [200 205 210 215 220 225 230 235 240 245 250 255 260 265 270 275 280 285
 290 295]


## 프로그래밍 문제 1-2: Python의 리스트 list_b 를 이용하여 위의 np.sum(array_b, axis=0)과 같은 계산을 수행하는 column_sum() 함수를 작성하시오.

NumPy의 array_b 배열을 Python의 기본 list_b 리스트로 변환

In [42]:
list_b = array_b.tolist()
print(list_b)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59], [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79], [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]


In [43]:
start_list2 = time.time()
def column_sum(b):
    sum_list = []
    number = 0
    for i in range(len(b[0])):
        elements_sum = 0
        for j in b:        #enumerate()함수 사용해보기.
            elements_sum += j[number]
        sum_list.append(elements_sum)
        number += 1
    return sum_list

위에 구현한 column_sum() 함수를 호출하여 반환된 결과값을 출력함.

In [44]:
# 함수 호출
column_sum_list = column_sum(list_b)
# 결과 출력
print("Column sum of list_b: ", column_sum_list)
end_list2 = time.time()
result_list2 = end_list2 - start_list2

Column sum of list_b:  [200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295]


NumPy의 np.sum()함수를 이용하여 각각의 행 별로 합을 구함.

In [45]:
start_array3 = time.time()
row_sum_array = np.sum(array_b, axis=1)
print("Row sum of array_b: ", row_sum_array)
end_array3 = time.time()
result_array3 = end_array3 - start_array3

Row sum of array_b:  [ 190  590  990 1390 1790]


## 프로그래밍 문제 1-3: Python의 리스트 list_b 를 이용하여 위의 np.sum(array_b, axis=1)과 같은 계산을 수행하는 row_sum() 함수를 작성하시오.

In [46]:
start_list3 = time.time()
def row_sum(b):
    sum_list = []
    for i in range(len(b)):
        elements_sum = 0
        for j in range(len(b[0])):     #enumerate()함수 사용해보기
            elements_sum += b[i][j]
        sum_list.append(elements_sum)
    return sum_list

위에 구현한 row_sum() 함수를 호출하여 반환된 결과값을 출력함.

In [47]:
# 함수 호출
row_sum_list = row_sum(list_b)
# 결과 출력
print("Row sum of list_b: ", row_sum_list)
end_list3 = time.time()
result_list3 = end_list3 - start_list3

Row sum of list_b:  [190, 590, 990, 1390, 1790]


# 문제 2 (5 points)
## 아래 주어진 NumPy의 array_c와 array_d를 갖고 문제 1의 순서대로 NumPy배열을 리스트로 변환한 후 np.max()와 같은 계산을 수행하는 find_max(), find_column_max(), find_row_max() 세개의 함수를 작성하시오. np.max() 와 구현한 함수로 부터 얻은 결과값을 비교하시오.

In [49]:
array_c = np.arange(0,200)
print(array_c)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]


## 프로그래밍 문제 2-1

In [50]:
start_array4 = time.time()
max_array = np.max(array_c)
print("Maximum value in array_c: ", max_array)
end_array4 = time.time()
result_array4 = end_array4 - start_array4

Maximum value in array_c:  199


In [51]:
start_list4 = time.time()
def find_max(c):
    for i in range(len(c)-1):
        if c[i + 1] > c[i]:
            max_elements = c[i + 1]
        elif c[i + 1] < c[i]:
            max_elements = c[i]
    return max_elements

In [52]:
# NumPy배열에서 리스트로 변환
list_c = array_c.tolist()

In [53]:
# 리스트를 입력값으로 하는 find_max() 함수 호출하여 결과값을 출력
max_list = find_max(list_c)
print("Maximum value in list_c: ", max_list)
end_list4 = time.time()
result_list4 = end_list4 - start_list4

Maximum value in list_c:  199


## 프로그래밍 문제 2-2

In [54]:
array_d = array_c.reshape(20,10)
print(array_d)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


In [55]:
start_array5 = time.time()
column_max_array = np.max(array_d, axis=0)
print("Maximum value of each column in array_d: ", column_max_array)
end_array5 = time.time()
result_array5 = end_array5 - start_array5

Maximum value of each column in array_d:  [190 191 192 193 194 195 196 197 198 199]


In [59]:
start_list5 = time.time()
def find_column_max(d):
    max_list = []
    for i in range(len(d[0])):
        for j in range(len(d)-1):
            if d[j + 1][i] > d[j][i]:
                max_elements = d[j + 1][i]
            elif d[j + 1][i] < d[j][i]:
                max_elements = d[j][i]
        max_list.append(max_elements)
    return max_list

In [60]:
# NumPy배열에서 리스트로 변환
list_d = array_d.tolist()

In [61]:
# 리스트를 입력값으로 하는 find_column_max() 함수 호출하여 결과값을 출력
column_max_list = find_column_max(list_d)
print("Maximum value of each column in list_d: ", column_max_list)
end_list5 = time.time()
result_list5 = end_list5 - start_list5

Maximum value of each column in list_d:  [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]


## 프로그래밍 문제 2-3

In [62]:
start_array6 = time.time()
row_max_array = np.max(array_d, axis=1)
print("Maximum value of each row in array_d: ", row_max_array)
end_array6 = time.time()
result_array6 = end_array6 - start_array6

Maximum value of each row in array_d:  [  9  19  29  39  49  59  69  79  89  99 109 119 129 139 149 159 169 179
 189 199]


In [63]:
start_list6 = time.time()
def find_row_max(d):
    max_list = []
    for i in range(len(d)):
        for j in range(len(d[0])-1):
            if d[i][j + 1] > d[i][j]:
                max_elements = d[i][j + 1]
            elif d[i][j + 1] < d[i][j]:
                max_elements = d[i][j]
        max_list.append(max_elements)
    return max_list

In [64]:
# 리스트를 입력값으로 하는 find_row_max() 함수 호출하여 결과값을 출력
row_max_list = find_row_max(list_d)
print("Maximum value of each row in list_d: ", row_max_list)
end_list6 = time.time()
result_list6 = end_list6 - start_list6

Maximum value of each row in list_d:  [9, 19, 29, 39, 49, 59, 69, 79, 89, 99, 109, 119, 129, 139, 149, 159, 169, 179, 189, 199]


# 문제 3 (1 point)
## NumPy에서 제공되는 함수(예: np.sum(), np.max() )와 list를 이용하여 직접 구현한 함수 (total_sum(), column_sum(), row_sum(), find_max(), find_column_max(), find_row_max() )의 실행 속도를 측정하여 비교하시오. (보충 설명: 위 문제 1과 문제 2에서 각각의 함수가 호출되어 실행된 셀안에서 실행시간을 측정하시오.)
(참고: %time 명령을 이용하거나(option 1) 아래 코드를 참고해서(option 2) 실행시간을 측정하시오.)

In [65]:
%time # option 1

print("")

import time # option 2
start = time.time()
# 코드 실행
print("hello")
end = time.time()
print(end - start)

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 4.77 µs

hello
7.724761962890625e-05


### 함수들의 실행시간를 보고(report)하고 얻은 결과를 바탕으로 결론을 요약해서 작성하시오.
(Markdown 과 Code를 활용하여 자유형식으로 아래에 결론을 작성 (셀 추가 가능) )

실행 속도: 아래 코드 부분처럼 각각의 함수 실행시간을 비교해보면 Numpy array의 함수 실행시간이 더 짧다.

결론:NumPy에서 제공되는 함수(np.sum(), np.max() )가 직접 구현한 함수 (total_sum(), column_sum(), row_sum(), find_max(), find_column_max(), find_row_max() )보다 실행시간이 짧은 것을 확인할 수 있었다.

In [66]:
if result_array1 < result_list1:
    print('Numpy의 array가 더 실행시간이 짧다.')
else:
    print('list가 실행시간이 짧다.')
if result_array2 < result_list2:
    print('Numpy의 array가 더 실행시간이 짧다.')
else:
    print('list가 실행시간이 짧다.')
if result_array3 < result_list3:
    print('Numpy의 array가 더 실행시간이 짧다.')
else:
    print('list가 실행시간이 짧다.')
if result_array4 < result_list4:
    print('Numpy의 array가 더 실행시간이 짧다.')
else:
    print('list가 실행시간이 짧다.')
if result_array5 < result_list5:
    print('Numpy의 array가 더 실행시간이 짧다.')
else:
    print('list가 실행시간이 짧다.')
if result_array6 < result_list6:
    print('Numpy의 array가 더 실행시간이 짧다.')
else:
    print('list가 실행시간이 짧다.')

Numpy의 array가 더 실행시간이 짧다.
Numpy의 array가 더 실행시간이 짧다.
Numpy의 array가 더 실행시간이 짧다.
Numpy의 array가 더 실행시간이 짧다.
Numpy의 array가 더 실행시간이 짧다.
Numpy의 array가 더 실행시간이 짧다.
